title: Rocket.Chat
description: The portal for all your Rocket.Chat documentation needs

url: https://rocketchat.github.io/www.rocket.chat
# permalink: /:year/:month/:day/:title/
paginate_path: /blog/page/:num/
paginate: 2

# bump if alterting styles
version: 5

# set default template for posts
defaults:
  - scope:
      type: posts
    values:
      layout: post

sass:
  style: compressed
  sass_dir: _sass

plugins_dir:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
