title: Rocket.Chat
description: The portal for all your Rocket.Chat documentation needs

url: https://rocket.chat
permalink: /:year/:month/:day/:title/
paginate_path: /blog/page/:num/
paginate: 8

# bump if alterting styles
version: 8

# read speed
wpm: 200

# set default template for posts
defaults:
  - scope:
      type: posts
    values:
      layout: post
      class: post
      
sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  
whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
